version: '3.2'

networks:
  pre-event-network:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: ${MYSQL_CONTAINER_NAME}
    volumes:
      - ./data/db_data:/var/lib/mysql:Z
      - ./mysql/init:/docker-entrypoint-initdb.d/:Z
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--skip-character-set-client-handshake'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - pre-event-network

  #Redis
  redis:
    container_name: ${REDIS_CONTAINER_NAME}
    image: redislabs/redismod:latest
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - pre-event-network
